[package]
name = "schnauzerUI"
version = "0.1.0"
edition = "2021"


[lib]
name = "schnauzer_ui"
path = "src/lib.rs"

[[bin]]
name = "sui"
path = "src/bin/cli.rs"

[dependencies]
async-recursion = "1.0.0"
chrono = "0.4.22"
log = "0.4.17"
simple-logging = "2.0.2"
thirtyfour = "0.31.0"
tokio = "1.21.2"
