[package]
name = "schnauzerUI"
version = "0.1.0"
edition = "2021"


[lib]
name = "schnauzer_ui"
path = "src/lib.rs"

[[bin]]
name = "sui"
path = "src/bin/cli.rs"

[dependencies]
async-recursion = "1.0.0"
chrono = "0.4.22"
clap = { version = "4.0.8", features = ["derive"] }
futures = "0.3.24"
thirtyfour = "0.31.0"
tokio = "1.21.2"
walkdir = "2.3.2"
